### ISSUE TITLE
Download links aren't working

### ISSUE THREAD

**Issue by nedjoni** [GameTec-live/ChameleonUltraGUI#517] opened 2024-10-29 07:51 UTC
As said in the title, I cannot access and download any of the installations for PC from the list. 
Luckily, it can still be installed from the Google Play Store.
Phone is nice for tinkering with CU, but PC is still more convenient.

**Comment by GameTec-live** [comment] 2024-10-29 09:01
what did you click on? short link or the nightly link?

**Comment by GameTec-live** [comment] 2024-10-29 09:22
ah

**Comment by GameTec-live** [comment] 2024-10-29 09:24
i think i know what the issue is... should be fixed when merging #501 
For now; download the one you want from actions directly... https://github.com/GameTec-live/ChameleonUltraGUI/actions/runs/11427767602

**Closed** 2024-10-29 09:27 UTC
